# Generated by Django 6.0.3 on 2026-03-31 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_shirt_size_alter_album_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='related editors'),
        ),
    ]
