# Generated by Django 6.0.3 on 2026-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_group_manufacturer_personae_place_poll_site_topping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("home_group", models.CharField(max_length=5)),
            ],
            options={
                "db_table": "Student_info",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ZipCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
