# Generated by Django 6.0.3 on 2026-04-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderedPerson",
            fields=[],
            options={
                "ordering": ["last_name"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("place.person",),
        ),
    ]
